(ns utils.constants)

(defonce users-collection-name "users")
(defonce languages-collection-name "languages")
(defonce os-collection-name "operating-systems")
(defonce countries-collection-name "countries")
(defonce catalogs-collection-name "catalogs")
(defonce categories-collection-name "categories")
(defonce companies-collection-name "companies")
(defonce products-collection-name "products")
(defonce tags-collection-name "tags")

(defonce my-global :my-global)
(defonce my-private :my-private)
(defonce my-public :my-public)
(defonce other-global :other-global)
(defonce other-private :other-private)
(defonce other-public :other-public)

(defonce database-name "Snowcrash")
(defonce database-host "127.0.0.1")
(defonce port 8822)

(defonce auth-header "authorization")
(defonce accept-language "accept-language")
(defonce default-status "active")
(defonce inactive-status "inactive")
(defonce default-empty-value "empty")

(defonce default-limit 10)
(defonce default-limit-str "10")
(defonce default-skip 0)
(defonce default-skip-str "0")